name: building.net application

on:
  push:

jobs:
  build_dot_net:
    runs-on: ubuntu-latest

    steps:
     - name: Set-up go
       uses: actions/setup-go@v4
       with:
        go-version: '1.16.0-beta.1' # The Go version to download (if necessary) and use.
     - run: go version

     - name: checkout source name
       uses: actions/checkout@v3

     - name: Run snapshot
       uses: actions/go-dependency-submission@v1
       with:
        go-mod-path: go.mod
        go-build-target: all

     - name: Deploy to Railway
       uses: bervProject/railway-deploy@main
       with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "assignment CICD"

     - name: Send custom JSON data to Slack workflow
       id: slack
       uses: slackapi/slack-github-action@v1.23.0
       with:
    # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name*: Lee Wei Xiang Vincent"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email*: vincelee7778@gmail.com"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation*: A112"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*: ${{ secrets.GH56_URL }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.RAILWAY_DOMAIN }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_DOMAIN }}"
                  }
                }
              ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          

        
        
        
