name: building.net application

on:
    push:

jobs:
  build_dot_net:
    runs-on: ubuntu-latest

    steps:
     - name: Set-up go
       uses: actions/setup-go@v4
       with:
        go-version: '1.16.0-beta.1' # The Go version to download (if necessary) and use.
     - run: go version

     - name: Run snapshot action
        uses: actions/go-dependency-submission@v1
        with:
            # Required: Define the repo path to the go.mod file used by the
            # build target
            go-mod-path: go-example/go.mod
            #
            # Optional: Define the path of a build target (a file with a
            # `main()` function) If not defined, this Action will collect all
            # dependencies used by all build targets for the module, which may
            # include Go dependencies used by tests and tooling.
            go-build-target: go-example/cmd/octocat.go
     - name: checkout source
       uses: actions/checkout@v3

     - name: Deploy to Railway
       uses: bervProject/railway-deploy@main
       with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "assignment CICD"

     
          

        
        
        
