name: Deploy golang application to Railway and publish the URL to Slack

on:
  push:
    branches:
    - 'release/v[0-9]+\.[0-9]+' # This regular expression pattern will match any branch 
    #name that starts with 'release/v' followed by one or more digits, a dot, and one or 
    #more digits.

jobs:
  condition_to_trigger:
    runs-on: ubuntu-latest

    steps:
      # Condition to run the action
    - name: Run workflow
      if: "!startsWith(github.event.head_commit.message, '#NORUN')"
      run: echo "Running the workflow"

    - name: Set-up go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16.0-beta.1' # The Go version to download (if necessary) and use.
    - run: go version

    - name: checkout source name
      uses: actions/checkout@v3

    # - name: Run snapshot
    #   uses: actions/go-dependency-submission@v1
    #   with:
    #     go-mod-path: go.mod
    #     go-build-target: all

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "assignment_CICD"

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 CI/CD Submission"  
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name*: ${{ vars.NAME }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email*: ${{ vars.EMAIL }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation*: ${{ vars.MATRICULATION }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*: https://github.com/${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.RAILWAY_DOMAIN }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_DOMAIN }}"
                  }
                }
              ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          

        
        
        
